---
- name: Check if Garage binary exists
  ansible.builtin.stat:
    path: "{{ garage_binary_path }}"
  register: _garage_binary

- name: Download and install Garage binary
  ansible.builtin.include_tasks: download.yml
  vars:
    _garage_download_force: false
  when: not _garage_binary.stat.exists
