---
driver:
  name: vagrant
  provider:
    name: libvirt

platforms:
  - name: garage-multidisk
    box: generic/debian12
    cpus: 1
    memory: 1024

provisioner:
  name: ansible
  lint: ansible-lint
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."

verifier:
  name: ansible
