---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: instance
    box: generic/debian12
    memory: 2048
    cpus: 1
    provider_options:
      driver: kvm
      qemu_use_session: false
provisioner:
  name: ansible
verifier:
  name: ansible
