---
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Check if Garage service is running
      ansible.builtin.systemd:
        name: garage
        state: started
        enabled: yes
      register: service_status
      failed_when: service_status.status.ActiveState != 'active'

    - name: Check if Garage RPC port is listening
      ansible.builtin.wait_for:
        port: 3901
        delay: 5
        timeout: 30
