---
- name: Converge
  hosts: all
  become: true
  vars:
    garage_rpc_secret: "ae6f6773bd8d1d26bf55843989d94642a0383e189f1fd5943d91a8ea0e565ac0"
    garage_replication_factor: 3
    garage_rpc_public_addr: "{{ ansible_default_ipv4.address }}:3901"
    garage_cluster_connect: true
    garage_layout_init: true
    garage_layout_zone: dc1
    garage_layout_capacity: 1G
    garage_healthcheck_enabled: true
  roles:
    - role: eyebrowkang.garage
